# keywords = {
#     "AND": "Logical AND operator.",
#     "DO": "Executes a block.",
#     "ELSE": "Alternative block.",
#     "EQ": "Equality check.",
#     "EXTEND": "Adds functionality.",
#     "FALSE": "Boolean false.",
#     "FOR": "Iterates over range.",
#     "FUN": "Function definition.",
#     "IF": "Conditional branch.",
#     "IMP": "Logical implication.",
#     "IN": "Membership check.",
#     "LOCAL": "Local variable.",
#     "LOCK": "Resource locking.",
#     "LOOP": "Iteration construct.",
#     "NAND": "Logical NAND operator.",
#     "NEQ": "Inequality check.",
#     "NOR": "Logical NOR operator.",
#     "NOT": "Logical NOT operator.",
#     "OR": "Logical OR operator.",
#     "SET": "Assigns a value.",
#     "STRUCT": "Defines a structure.",
#     "THEN": "Consequent block.",
#     "THIS": "Current instance.",
#     "TRUE": "Boolean true.",
#     "WHILE": "Loop with condition.",
#     "XOR": "Exclusive OR operator.",
# }
# reserved_help = keywords

reserved_hover_helper_dict = {
    "TRUE": "HELPER_TRUE: ",
    "STRUCT": "HELPER_STRUCT: ",
    "DO": "HELPER_DO: ",
    "NOR": "HELPER_NOR: ",
    "THIS": "HELPER_THIS: ",
    "WHILE": "HELPER_WHILE: ",
    "EQ": "HELPER_EQ: ",
    "THEN": "HELPER_THEN: ",
    "NAND": "HELPER_NAND: ",
    "IMP": "HELPER_IMP: ",
    "NEQ": "HELPER_NEQ: ",
    "IF": "HELPER_IF: ",
    "IN": "HELPER_IN: ",
    "AND": "HELPER_AND: ",
    "XOR": "HELPER_XOR: ",
    "SET": "HELPER_SET: ",
    "ELSE": "HELPER_ELSE: ",
    "LOOP": "HELPER_LOOP: ",
    "LOCK": "HELPER_LOCK: ",
    "FUN": "HELPER_FUN: ",
    "FALSE": "HELPER_FALSE: ",
    "NOT": "HELPER_NOT: ",
    "LOCAL": "HELPER_LOCAL: ",
    "EXTEND": "HELPER_EXTEND: ",
    "OR": "HELPER_OR: ",
    "FOR": "HELPER_FOR: ",
}
